CREATE DATABASE DWH_Project
GO

USE DWH_Project
GO

CREATE TABLE DimProduct (
	ProductID INT NOT NULL PRIMARY KEY,
	ProductName VARCHAR(255) NOT NULL,
	ProductCategory VARCHAR(255) NOT NULL,
	ProductUnitPrice INT
)
GO

CREATE TABLE DimCustomer (
	CustomerID INT NOT NULL PRIMARY KEY,
	CustomerName VARCHAR(255) NOT NULL,
	Age INT NOT NULL,
	Gender VARCHAR(50) NOT NULL,
	City VARCHAR(50) NOT NULL,
	NoHP VARCHAR(50) NOT NULL
)
GO

CREATE TABLE DimStatusOrder (
	StatusID INT NOT NULL PRIMARY KEY,
	StatusOrder VARCHAR(50) NOT NULL,
	StatusOrderDesc VARCHAR(50) NOT NULL
)
GO

CREATE TABLE FactSalesOrder (
	OrderID INT NOT NULL PRIMARY KEY,
	CustomerID INT NOT NULL FOREIGN KEY REFERENCES DimCustomer(CustomerID),
	ProductID INT NOT NULL FOREIGN KEY REFERENCES DimProduct(ProductID),
	Quantity INT NOT NULL,
	Amount INT NOT NULL,
	StatusID INT NOT NULL FOREIGN KEY REFERENCES DimStatusOrder(StatusID),
	OrderDate DATE NOT NULL
)
GO